version: "3.3"

services:
  mysql:
    image: mysql:8
    container_name: docker-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=session_redis
  redis:
    image: redis
    container_name: docker-redis
    ports:
      - "6379:6379"
  nginx:
    image: nginx
    container_name: docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  spring-server1:
    image: spring-server1
    container_name: docker-server1
    ports:
      - "18080:8080"
    depends_on:
      - mysql
      - redis
    restart: always
  spring-server2:
    image: spring-server2
    container_name: docker-server2
    ports:
      - "18081:8080"
    depends_on:
      - mysql
      - redis
    restart: always